project:
  type: website

website:
  title: "sib-bc2-workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - analysis.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



